
[functions.cakto-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = true

[functions.create-cakto-checkout]
verify_jwt = true

[functions.kiwify-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true
