// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfqzgwyzzmotzqkpjnfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcXpnd3l6em1vdHpxa3BqbmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzY3NjcsImV4cCI6MjA2MDgxMjc2N30.BCkMpjZorMIOzoi_uW7oA0-78xVcCAQFjlp_L8f4Sb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);